
const busData = [
    {
       id:1, name :"Intercity Smart Bus",
       seatType :["A/C Sleeper(2+1)","|","Left Seat","|","Window Seat"], 
       seatInfo:["Live Tracking","Policies","Photos","Amenities","Review"],
       rating:"4.5",
       price:"$899",
       depTime:"22:45,16NOV",
       arrTime:"06:20,17NOV",
       timeduration:"07hrs59min",
       pickPoint: "Delhi",
       dropPoint: "Mumbai",
    },
    {
        id:2, name :"Zing Smart Bus",
        seatType :["A/C Sleeper(2+1)","|","Left Seat","|","Window Seat"], 
        seatInfo:["Live Tracking","Policies","Photos","Amenities","Review"],
        rating:"4.5",
        price:"$899",
        depTime:"22:45,16NOV",
        arrTime:"06:20,17NOV",
        timeduration:"07hrs59min",
        pickPoint: "Mumbai",
        dropPoint: "Delhi",
     },
     {
        id:3, name :"Safar Exppress Bus",
        seatType :["A/C Sleeper(2+1)","|","Left Seat","|","Window Seat"], 
        seatInfo:["Live Tracking","Policies","Photos","Amenities","Review"],
        rating:"4",
        price:"$899",
        depTime:"22:45,16NOV",
        arrTime:"06:20,17NOV",
        timeduration:"07hrs59min",
        pickPoint: "Mumbai",
        dropPoint: "Hedrabad",
     },
     {
        id:4, name :"Intercity Smart Bus",
        seatType :["A/C Sleeper(2+1)","|","Left Seat","|","Window Seat"], 
        seatInfo:["Live Tracking","Policies","Photos","Amenities","Review"],
        rating:"4.5",
        price:"$899",
        depTime:"22:45,16NOV",
        arrTime:"06:20,17NOV",
        timeduration:"07hrs59min",
        pickPoint: "Hedrabad",
        dropPoint: "Mumbai",
     },
     {
         id:5, name :"Zing Smart Bus",
         seatType :["A/C Sleeper(2+1)","|","Left Seat","|","Window Seat"], 
         seatInfo:["Live Tracking","Policies","Photos","Amenities","Review"],
         rating:"3.5",
         price:"$899",
         depTime:"22:45,16NOV",
         arrTime:"06:20,17NOV",
         timeduration:"07hrs59min",
         pickPoint: "Delhi",
         dropPoint: "Hedrabad",
      },
      {
         id:6, name :"Safar Exppress Bus",
         seatType :["A/C Sleeper(2+1)","|","Left Seat","|","Window Seat"], 
         seatInfo:["Live Tracking","Policies","Photos","Amenities","Review"],
         rating:"3",
         price:"$899",
         depTime:"22:45,16NOV",
         arrTime:"06:20,17NOV",
         timeduration:"07hrs59min",
         pickPoint: "Hedrabad",
         dropPoint: "Delhi",
      },
     
];
export default busData;
