import seat from "../images/seat.png";

const busSeatData = [
  {
    id: 1,
    prices: "599",
    seatInfo: [
      { id: 1, value: "Vacant Seats", selected: false },
      { id: 2, value: "Reserved Seats", selected: false },
      { id: 3, value: "Selexted Seats", selected: false },
    ],
    seatLeft: [
      { id: 1, price: "599", value: seat, selected: false },
      { id: 2, price: "599", value: seat, selected: false },
      { id: 3, price: "599", value: seat, selected: false },
      { id: 4, price: "599", value: seat, selected: false },
      { id: 5, price: "599", value: seat, selected: false },
      { id: 6, price: "599", value: seat, selected: false },
      { id: 7, price: "599", value: seat, selected: false },
    ],
    seatMid: [
      { id: 8, price: "599", value: seat, selected: false },
      { id: 9, price: "599", value: seat, selected: false },
      { id: 10, price: "599", value: seat, selected: false },
      { id: 11, price: "599", value: seat, selected: false },
      { id: 12, price: "599", value: seat, selected: false },
      { id: 13, price: "599", value: seat, selected: false },
      { id: 14, price: "599", value: seat, selected: false },
    ],
    seatRight: [
      { id: 15, price: "599", value: seat, selected: false },
      { id: 16, price: "599", value: seat, selected: false },
      { id: 17, price: "599", value: seat, selected: false },
      { id: 18, price: "599", value: seat, selected: false },
      { id: 19, price: "599", value: seat, selected: false },
    ],
  },
  {
    id: 2,
    prices: "699",
    seatInfo: [
      { id: 1, value: "Vacant Seats", selected: false },
      { id: 2, value: "Reserved Seats", selected: false },
      { id: 3, value: "Selexted Seats", selected: false },
    ],
    seatLeft: [
      { id: 1, price: "699", value: seat, selected: false },
      { id: 2, price: "699", value: seat, selected: false },
      { id: 3, price: "699", value: seat, selected: false },
      { id: 4, price: "699", value: seat, selected: false },
      { id: 5, price: "699", value: seat, selected: false },
      { id: 6, price: "699", value: seat, selected: false },
      { id: 7, price: "699", value: seat, selected: false },
    ],
    seatMid: [
      { id: 8, price: "699", value: seat, selected: false },
      { id: 9, price: "699", value: seat, selected: false },
      { id: 10, price: "699", value: seat, selected: false },
      { id: 11, price: "699", value: seat, selected: false },
      { id: 12, price: "699", value: seat, selected: false },
      { id: 13, price: "699", value: seat, selected: false },
      { id: 14, price: "699", value: seat, selected: false },
    ],
    seatRight: [
      { id: 15, price: "699", value: seat, selected: false },
      { id: 16, price: "699", value: seat, selected: false },
      { id: 17, price: "699", value: seat, selected: false },
      { id: 18, price: "699", value: seat, selected: false },
      { id: 19, price: "699", value: seat, selected: false },
    ],
  },
  {
    id: 3,
    prices: "899",
    seatInfo: [
      { id: 1, value: "Vacant Seats", selected: false },
      { id: 2, value: "Reserved Seats", selected: false },
      { id: 3, value: "Selexted Seats", selected: false },
    ],
    seatLeft: [
      { id: 1, price: "899", value: seat, selected: false },
      { id: 2, price: "899", value: seat, selected: false },
      { id: 3, price: "899", value: seat, selected: false },
      { id: 4, price: "899", value: seat, selected: false },
      { id: 5, price: "899", value: seat, selected: false },
      { id: 6, price: "899", value: seat, selected: false },
      { id: 7, price: "899", value: seat, selected: false },
    ],
    seatMid: [
      { id: 8, price: "899", value: seat, selected: false },
      { id: 9, price: "899", value: seat, selected: false },
      { id: 10, price: "899", value: seat, selected: false },
      { id: 11, price: "899", value: seat, selected: false },
      { id: 12, price: "899", value: seat, selected: false },
      { id: 13, price: "899", value: seat, selected: false },
      { id: 14, price: "899", value: seat, selected: false },
    ],
    seatRight: [
      { id: 15, price: "899", value: seat, selected: false },
      { id: 16, price: "899", value: seat, selected: false },
      { id: 17, price: "899", value: seat, selected: false },
      { id: 18, price: "899", value: seat, selected: false },
      { id: 19, price: "899", value: seat, selected: false },
    ],
  },
  {
    id: 4,
    prices: "1199",
    seatInfo: [
      { id: 1, value: "Vacant Seats", selected: false },
      { id: 2, value: "Reserved Seats", selected: false },
      { id: 3, value: "Selexted Seats", selected: false },
    ],
    seatLeft: [
      { id: 1, price: "1199", value: seat, selected: false },
      { id: 2, price: "1199", value: seat, selected: false },
      { id: 3, price: "1199", value: seat, selected: false },
      { id: 4, price: "1199", value: seat, selected: false },
      { id: 5, price: "1199", value: seat, selected: false },
      { id: 6, price: "1199", value: seat, selected: false },
      { id: 7, price: "1199", value: seat, selected: false },
    ],
    seatMid: [
      { id: 8, price: "1199", value: seat, selected: false },
      { id: 9, price: "1199", value: seat, selected: false },
      { id: 10, price: "1199", value: seat, selected: false },
      { id: 11, price: "1199", value: seat, selected: false },
      { id: 12, price: "1199", value: seat, selected: false },
      { id: 13, price: "1199", value: seat, selected: false },
      { id: 14, price: "1199", value: seat, selected: false },
    ],
    seatRight: [
      { id: 15, price: "1199", value: seat, selected: false },
      { id: 16, price: "1199", value: seat, selected: false },
      { id: 17, price: "1199", value: seat, selected: false },
      { id: 18, price: "1199", value: seat, selected: false },
      { id: 19, price: "1199", value: seat, selected: false },
    ],
  },
];

export default busSeatData;
