const actionTypes = {

    INITIALIZE: 'INITIALIZE',
    BUSDETAIL_API_SUCCESS: 'BUSDETAIL_API_SUCCESS',
    BUSDETAIL_API_ERROR: 'BUSDETAIL_API_ERROR',

    LOCTION_SUCCESS: 'LOCTION_SUCCESS',
    LOCATION_ERROR: 'LOCATION_ERROR',
}

export default actionTypes